/// Flutter icons BYRIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BYRIcons
///      fonts:
///       - asset: fonts/BYRIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BYRIcons {
  BYRIcons._();

  static const _kFontFam = 'BYRIcons';
  static const _kFontPkg = null;

  static const IconData user_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_butterfly = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_butterfly_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dizzy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dizzy_solid = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle_solid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dots_solid = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dots = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
