// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'translator.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BYRTranslator _$BYRTranslatorFromJson(Map<String, dynamic> json) {
  return BYRTranslator(
    json['translatorName'] as String,
    json['translatorDisplayName'] as String,
    json['byrTrans'] as String,
    json['loginUsernameTrans'] as String,
    json['loginPasswordTrans'] as String,
    json['loginSubmitTrans'] as String,
    json['loginForgetPasswordTrans'] as String,
    json['loginSignUpTrans'] as String,
    json['logoutTrans'] as String,
    json['addAccount'] as String,
    json['toptenTrans'] as String,
    json['timelineTrans'] as String,
    json['subscribedTrans'] as String,
    json['boardmarksTrans'] as String,
    json['boardTrans'] as String,
    json['backToBoardTrans'] as String,
    json['participantsTrans'] as String,
    json['repliersTrans'] as String,
    json['noThreadTodayTrans'] as String,
    json['newThreadTodayTrans'] as String,
    json['newThreadsTodayTrans'] as String,
    json['threadTrans'] as String,
    json['hotRepliesTrans'] as String,
    json['allRepliesTrans'] as String,
    json['replycontentTrans'] as String,
    json['replyingTrans'] as String,
    json['reportTrans'] as String,
    json['reportConfirmTrans'] as String,
    (json['positionTrans'] as List)?.map((e) => e as String)?.toList(),
    json['submitTrans'] as String,
    json['aboutTrans'] as String,
    json['skipTrans'] as String,
    json['aboutButtonTrans'] as String,
    json['sectionButtonTrans'] as String,
    json['collectionTrans'] as String,
    json['subSectionTrans'] as String,
    json['downloadImageTrans'] as String,
    json['saveTrans'] as String,
    json['confirmTrans'] as String,
    json['cancelTrans'] as String,
    json['boardNameEn'] as bool,
    json['updatedOn'] as String,
    json['timeTodayTrans'] as String,
    json['timeYesterdayTrans'] as String,
    json['stickyTopTrans'] as String,
    json['search'] as String,
    json['browseWebPageTrans'] as String,
    json['anonymous'] as String,
    json['unAnonymous'] as String,
    json['themeAuto'] as String,
    json['themeAdd'] as String,
    json['themeRemove'] as String,
    json['succeed'] as String,
    json['fail'] as String,
    json['update'] as String,
    json['newVersion'] as String,
    json['ignoreVersion'] as String,
    json['replyReferTrans'] as String,
    json['atReferTrans'] as String,
    json['smsTrans'] as String,
    json['replyTrans'] as String,
    json['sendTrans'] as String,
    json['messageTrans'] as String,
    json['allReadTrans'] as String,
    json['receiverTrans'] as String,
    json['titleTrans'] as String,
    json['contentTrans'] as String,
    json['nonBlankTrans'] as String,
    json['sendSuccessTrans'] as String,
    json['sendFailedTrans'] as String,
    json['jumpPage'] as String,
    json['current'] as String,
    json['page'] as String,
    json['original'] as String,
    json['link'] as String,
    json['pleaseInputPage'] as String,
    json['downloadAtt'] as String,
    json['postArticle'] as String,
    json['uploadLimit'] as String,
    json['selectBoard'] as String,
    json['cantFindBoard'] as String,
    json['uploadExceedLimit'] as String,
    json['notAllowAtt'] as String,
    json['upload'] as String,
    json['camera'] as String,
    json['gallery'] as String,
    json['share'] as String,
    json['onlyAuthor'] as String,
    json['emoji'] as String,
    json['color'] as String,
    json['close'] as String,
    json['preview'] as String,
    json['useIPv4'] as String,
    json['useIPv6'] as String,
    json['threads'] as String,
    json['hasFavorite'] as String,
    json['favorite'] as String,
    json['removeCollectionTrans'] as String,
    json['dismissReplyPointerTrans'] as String,
    (json['emojiTrans'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k, e as String),
    ),
    json['audioFileTrans'] as String,
    json['audioRecordTrans'] as String,
    json['audioPostWarning'] as String,
    json['betTrans'] as String,
    (json['betAttriTypesTrans'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k, e as String),
    ),
    json['betOnTrans'] as String,
    json['betStakeTrans'] as String,
    json['betPotentialCollectTrans'] as String,
    json['minimumBetTrans'] as String,
    json['myTokenBalanceTrans'] as String,
    json['allinTrans'] as String,
    json['betEndTrans'] as String,
    json['voteTypeMultiple'] as String,
    json['voteTypeSingle'] as String,
    json['voteLimit'] as String,
    json['userVoted'] as String,
    json['resultAfterVote'] as String,
    json['vote'] as String,
    json['voteLimitAlert'] as String,
    (json['voteAttriTypesTrans'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k, e as String),
    ),
    json['copy'] as String,
    json['delete'] as String,
    json['deleting'] as String,
    json['deleteSuccess'] as String,
    json['deleteFailed'] as String,
    json['edit'] as String,
    json['hiddenByVotedown'] as String,
    json['letmeseesee'] as String,
    json['profilePageName'] as String,
    json['profileLife'] as String,
    json['profilePostCount'] as String,
    json['profileScore'] as String,
    json['profileLevel'] as String,
    json['profileState'] as String,
    json['profileOnline'] as String,
    json['profileOffline'] as String,
    json['profileStarSign'] as String,
    json['profileHomePage'] as String,
    json['profileQQ'] as String,
    json['titleKeywords'] as String,
    json['authorId'] as String,
    json['timeRage'] as String,
    json['unlimited'] as String,
    json['oneWeek'] as String,
    json['oneMonth'] as String,
    json['oneYear'] as String,
    json['attach'] as String,
    json['withAttach'] as String,
    json['withoutAttach'] as String,
    json['searchNoResults'] as String,
    json['searchHintPart1'] as String,
    json['searchHintPart2'] as String,
    json['loadIDLE'] as String,
    json['loadFailed'] as String,
    json['loadCan'] as String,
    json['noMoreData'] as String,
    json['homePage'] as String,
    json['discover'] as String,
    json['me'] as String,
    json['frontTabSettingsTrans'] as String,
    json['pullUpToScreenshot'] as String,
    json['releaseToScreenshot'] as String,
    json['screenshotFailed'] as String,
    json['screenshotCaptured'] as String,
    json['networkExceptionTrans'] as String,
    json['dataExceptionTrans'] as String,
    json['toptenScreenshotTrans'] as String,
    json['screenshotPage'] as String,
    json['screenshotOverLength'] as String,
    json['externalBrowser'] as String,
    json['language'] as String,
    json['networkType'] as String,
    json['settings'] as String,
    json['publicTesting'] as String,
    json['importThemeNotification'] as String,
    json['refresherSettings'] as String,
    json['importRefresherNotification'] as String,
    json['refresherAdd'] as String,
    json['downgradeTrans'] as String,
  );
}

Map<String, dynamic> _$BYRTranslatorToJson(BYRTranslator instance) => <String, dynamic>{
      'translatorName': instance.translatorName,
      'translatorDisplayName': instance.translatorDisplayName,
      'byrTrans': instance.byrTrans,
      'loginUsernameTrans': instance.loginUsernameTrans,
      'loginPasswordTrans': instance.loginPasswordTrans,
      'loginSubmitTrans': instance.loginSubmitTrans,
      'loginForgetPasswordTrans': instance.loginForgetPasswordTrans,
      'loginSignUpTrans': instance.loginSignUpTrans,
      'logoutTrans': instance.logoutTrans,
      'addAccount': instance.addAccount,
      'toptenTrans': instance.toptenTrans,
      'timelineTrans': instance.timelineTrans,
      'subscribedTrans': instance.subscribedTrans,
      'boardmarksTrans': instance.boardmarksTrans,
      'boardTrans': instance.boardTrans,
      'backToBoardTrans': instance.backToBoardTrans,
      'participantsTrans': instance.participantsTrans,
      'repliersTrans': instance.repliersTrans,
      'noThreadTodayTrans': instance.noThreadTodayTrans,
      'newThreadTodayTrans': instance.newThreadTodayTrans,
      'newThreadsTodayTrans': instance.newThreadsTodayTrans,
      'threadTrans': instance.threadTrans,
      'hotRepliesTrans': instance.hotRepliesTrans,
      'allRepliesTrans': instance.allRepliesTrans,
      'replycontentTrans': instance.replycontentTrans,
      'replyingTrans': instance.replyingTrans,
      'reportTrans': instance.reportTrans,
      'reportConfirmTrans': instance.reportConfirmTrans,
      'positionTrans': instance.positionTrans,
      'submitTrans': instance.submitTrans,
      'aboutTrans': instance.aboutTrans,
      'skipTrans': instance.skipTrans,
      'aboutButtonTrans': instance.aboutButtonTrans,
      'sectionButtonTrans': instance.sectionButtonTrans,
      'collectionTrans': instance.collectionTrans,
      'subSectionTrans': instance.subSectionTrans,
      'downloadImageTrans': instance.downloadImageTrans,
      'saveTrans': instance.saveTrans,
      'confirmTrans': instance.confirmTrans,
      'cancelTrans': instance.cancelTrans,
      'boardNameEn': instance.boardNameEn,
      'updatedOn': instance.updatedOn,
      'timeTodayTrans': instance.timeTodayTrans,
      'timeYesterdayTrans': instance.timeYesterdayTrans,
      'stickyTopTrans': instance.stickyTopTrans,
      'search': instance.search,
      'browseWebPageTrans': instance.browseWebPageTrans,
      'anonymous': instance.anonymous,
      'unAnonymous': instance.unAnonymous,
      'themeAuto': instance.themeAuto,
      'themeAdd': instance.themeAdd,
      'themeRemove': instance.themeRemove,
      'succeed': instance.succeed,
      'fail': instance.fail,
      'update': instance.update,
      'newVersion': instance.newVersion,
      'ignoreVersion': instance.ignoreVersion,
      'replyReferTrans': instance.replyReferTrans,
      'atReferTrans': instance.atReferTrans,
      'smsTrans': instance.smsTrans,
      'replyTrans': instance.replyTrans,
      'sendTrans': instance.sendTrans,
      'messageTrans': instance.messageTrans,
      'allReadTrans': instance.allReadTrans,
      'receiverTrans': instance.receiverTrans,
      'titleTrans': instance.titleTrans,
      'contentTrans': instance.contentTrans,
      'nonBlankTrans': instance.nonBlankTrans,
      'sendSuccessTrans': instance.sendSuccessTrans,
      'sendFailedTrans': instance.sendFailedTrans,
      'jumpPage': instance.jumpPage,
      'current': instance.current,
      'page': instance.page,
      'original': instance.original,
      'link': instance.link,
      'pleaseInputPage': instance.pleaseInputPage,
      'downloadAtt': instance.downloadAtt,
      'postArticle': instance.postArticle,
      'uploadLimit': instance.uploadLimit,
      'selectBoard': instance.selectBoard,
      'cantFindBoard': instance.cantFindBoard,
      'uploadExceedLimit': instance.uploadExceedLimit,
      'notAllowAtt': instance.notAllowAtt,
      'upload': instance.upload,
      'camera': instance.camera,
      'gallery': instance.gallery,
      'share': instance.share,
      'onlyAuthor': instance.onlyAuthor,
      'emoji': instance.emoji,
      'color': instance.color,
      'close': instance.close,
      'preview': instance.preview,
      'useIPv4': instance.useIPv4,
      'useIPv6': instance.useIPv6,
      'threads': instance.threads,
      'hasFavorite': instance.hasFavorite,
      'favorite': instance.favorite,
      'removeCollectionTrans': instance.removeCollectionTrans,
      'dismissReplyPointerTrans': instance.dismissReplyPointerTrans,
      'emojiTrans': instance.emojiTrans,
      'audioFileTrans': instance.audioFileTrans,
      'audioRecordTrans': instance.audioRecordTrans,
      'audioPostWarning': instance.audioPostWarning,
      'betTrans': instance.betTrans,
      'betAttriTypesTrans': instance.betAttriTypesTrans,
      'betOnTrans': instance.betOnTrans,
      'betStakeTrans': instance.betStakeTrans,
      'betPotentialCollectTrans': instance.betPotentialCollectTrans,
      'minimumBetTrans': instance.minimumBetTrans,
      'myTokenBalanceTrans': instance.myTokenBalanceTrans,
      'allinTrans': instance.allinTrans,
      'betEndTrans': instance.betEndTrans,
      'voteTypeMultiple': instance.voteTypeMultiple,
      'voteTypeSingle': instance.voteTypeSingle,
      'voteLimit': instance.voteLimit,
      'userVoted': instance.userVoted,
      'resultAfterVote': instance.resultAfterVote,
      'vote': instance.vote,
      'voteLimitAlert': instance.voteLimitAlert,
      'voteAttriTypesTrans': instance.voteAttriTypesTrans,
      'copy': instance.copy,
      'delete': instance.delete,
      'deleting': instance.deleting,
      'deleteSuccess': instance.deleteSuccess,
      'deleteFailed': instance.deleteFailed,
      'edit': instance.edit,
      'hiddenByVotedown': instance.hiddenByVotedown,
      'letmeseesee': instance.letmeseesee,
      'profilePageName': instance.profilePageName,
      'profileLife': instance.profileLife,
      'profilePostCount': instance.profilePostCount,
      'profileScore': instance.profileScore,
      'profileLevel': instance.profileLevel,
      'profileState': instance.profileState,
      'profileOnline': instance.profileOnline,
      'profileOffline': instance.profileOffline,
      'profileStarSign': instance.profileStarSign,
      'profileHomePage': instance.profileHomePage,
      'profileQQ': instance.profileQQ,
      'titleKeywords': instance.titleKeywords,
      'authorId': instance.authorId,
      'timeRage': instance.timeRage,
      'unlimited': instance.unlimited,
      'oneWeek': instance.oneWeek,
      'oneMonth': instance.oneMonth,
      'oneYear': instance.oneYear,
      'attach': instance.attach,
      'withAttach': instance.withAttach,
      'withoutAttach': instance.withoutAttach,
      'searchNoResults': instance.searchNoResults,
      'searchHintPart1': instance.searchHintPart1,
      'searchHintPart2': instance.searchHintPart2,
      'loadIDLE': instance.loadIDLE,
      'loadFailed': instance.loadFailed,
      'loadCan': instance.loadCan,
      'noMoreData': instance.noMoreData,
      'homePage': instance.homePage,
      'discover': instance.discover,
      'me': instance.me,
      'frontTabSettingsTrans': instance.frontTabSettingsTrans,
      'pullUpToScreenshot': instance.pullUpToScreenshot,
      'releaseToScreenshot': instance.releaseToScreenshot,
      'screenshotFailed': instance.screenshotFailed,
      'screenshotCaptured': instance.screenshotCaptured,
      'networkExceptionTrans': instance.networkExceptionTrans,
      'dataExceptionTrans': instance.dataExceptionTrans,
      'toptenScreenshotTrans': instance.toptenScreenshotTrans,
      'screenshotPage': instance.screenshotPage,
      'screenshotOverLength': instance.screenshotOverLength,
      'externalBrowser': instance.externalBrowser,
      'language': instance.language,
      'networkType': instance.networkType,
      'settings': instance.settings,
      'publicTesting': instance.publicTesting,
      'importThemeNotification': instance.importThemeNotification,
      'refresherSettings': instance.refresherSettings,
      'importRefresherNotification': instance.importRefresherNotification,
      'refresherAdd': instance.refresherAdd,
      'downgradeTrans': instance.downgradeTrans,
    };
